### ISSUE TITLE
Explode filter isn't working

### ISSUE THREAD

**Issue by quinnanya** [backdrop-contrib/feeds_tamper#14]
Thanks for porting this module! I've been having trouble with the Explode filter -- not only does it not explode multiple values, it also seems to cause problems for non-multi-valued fields to be imported. I've tried to use it with an image field (mapping URIs) and with a node reference field (mapping NIDs). In the image field, at least, having the filter enabled means that no images get imported, even the ones that don't have multiple values.

Happy to test things / send reports, if it'd be useful!

**Comment by laryn** [comment]
@quinnanya Can you provide a screenshot of your tamper settings and a line or two from the import sheet?

**Comment by efc8d** [comment]
Hi @laryn, picking up for @quinnanya here. There are a couple of things going on, the first of which is that the site is using the entity references module which doesn't allow for anything to come in with feeds actually. If instead we switch to a node reference field from the References module, non-multi-value fields are able to come in. In either instance the explode filter returns the below errors after an import is attempted. I've attached a screenshot of the current explode settings and we have also tried setting the string separator without the %s. A non multi value in the spreadsheet is formatted as Leonard Woolf and a multi value is formatted as Vita Sackville-West | Leonard Woolf
`Notice: Undefined index: real_separator in feeds_tamper_explode_callback() (line 58 of /home/modernis/backdropdebug.modernistarchives.com/modules/feeds_tamper/plugins/explode.inc).
Warning: explode(): Empty delimiter in feeds_tamper_explode_callback() (line 58 of /home/modernis/backdropdebug.modernistarchives.com/modules/feeds_tamper/plugins/explode.inc).
Warning: array_merge(): Argument #2 is not an array in feeds_tamper_explode_callback() (line 58 of /home/modernis/backdropdebug.modernistarchives.com/modules/feeds_tamper/plugins/explode.inc).`
<img width="1258" alt="Screen Shot 2021-04-20 at 7 47 50 PM" src="https://user-images.githubusercontent.com/7092916/115477150-4d4d7e00-a211-11eb-9f08-e3ba96f05368.png">

**Comment by albanycomputers** [comment]
Also having a problem with the Explode.

I'm trying to add a multi-value taxonomy i.e.   "Award Type > Cups".. I have tried with %s and also removing the spaces... I've also replaced the ">" with a comma.

The error on running the import is "Missing bundle property on entity of type taxonomy_term."

When I then go back to edit the Tamper section, the "Plugin" is no longer there.  I've re-added a few times and experimented with different settings, although there aren't that many to play with... and it still vanishes if the "Node processor / Mapping" is edited and saved.

**Comment by albanycomputers** [comment]
I've just been experimenting with Feeds-tamper... 

I added an explode and also a Trim to a description field... this seemed to save both of them... and when I go into "Edit - mappings" and return to Tamper, they are still there... yesterday I only added the Explode which disappeared after the "Edit - mappings" was changed.

So, I tried the import again and still getting the same message "Missing bundle property on entity of type taxonomy_term."

So, I removed the Explode and I'm still getting the same error message, so It could be that it's the taxonomy side of the Feeds importer that's having a problem.

In the "Categories" taxonomy, the file had "Award Type,Cups"... I have removed the ",Cups" and tried to import again but left the "auto create" turned off and this time it worked.

I changed the Mappings to "Auto create" = yes and it failed again with the same error.

It seems as though the Taxonomy creation is having a problem.

I have changed the Categories in the file from "Award Type" and replaced the Category with one that already exists so it shouldn't need to auto-create it... and it produces the same error.

Tried again with the Auto-Create disabled and the import worked but the Taxonomy wasn't highlighted in the node content.

Hope this helps.

**Comment by albanycomputers** [comment]
Just deleted all content (I'm only experimenting with a 15 item import)

Tried again and the import worked but not the taxonomy.

Just deleted the import again and changed the "Taxonomy name" to the "Taxonomy ID" and this worked, it's added the taxonomy to the product.

**Comment by albanycomputers** [comment]
Steve Moorhouse13:35
In the import file... I changed the Taxonomy Name to the ID number and it imported it.

Changed "Achievement" to number "1"

--

I've just added a Taxonomy Term and a child term manually to the website.

Changed the import file for Categories from "Award Type,Cups" to "2,3" and used the "Explode" Feeds tamper...

And it worked... but It added the node to both the Main category and its child...

I thought it would only add it to the child term.

Seems to be the "Feeds" and not the "Explode" that's got the bug.

**Comment by efc8d** [comment]
Hi @albanycomputers,

You might try looking at this PR https://github.com/backdrop-contrib/feeds/issues/89 for the taxonomy import issue. I added this early on and haven't had any issues with taxonomy terms by term name and auto create.

An update on the issue both I and quinnanya were having. Explode is working on a clean install of the site. The issues arose when dealing with a site converted from D7 to Backdrop. Not sure what was causing them, but there were several errors, not just Explode that made it more feasible just to do everything as a clean install with multiple imports.

**Comment by albanycomputers** [comment]
Hi @efc8d

I'll have a look, thanks.

The site I'm working on is a fresh BD site.

**Comment by laryn** [comment]
Is anyone still having issues with explode? I think I'll close this for now as stale -- please reopen or file a new issue if you are seeing problems.
