### ISSUE TITLE
Please add a wiki page...

### ISSUE THREAD

**Issue by albanycomputers** [backdrop-contrib/feeds_tamper#18]
Can you please add a wiki page for help and support?

I've spent a few hours trying to import a CSV file with a UK date format..., for example... 18/12/2023 and it failed.

I've tried a number of solutions without any joy...

On researching, I found a solution that was posted on StackOverflow 13 years ago :-)

``` quote
Dates in the m/d/y or d-m-y formats are disambiguated by looking at the separator between the various components:
if the separator is a slash (/), then the American m/d/y is assumed; 
whereas if the separator is a dash (-) or a dot (.), then the European d-m-y format is assumed.
```

Anyway :) Adding the wiki would help people post solutions in one place.

**Comment by laryn** [comment]
@albanycomputers I've unlocked the Wiki -- have at it!
