### ISSUE TITLE
"Call to undefined function feeds_tamper_explode_validate()"

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/feeds_tamper#3]
On trying to add an 'explode' tamper, I get this error:

> Call to undefined function feeds_tamper_explode_validate()

This seems to be a result of moving code around in the module (in D7 the call to this function was in the same file as the function, whereas in Backdrop it's been separated into different files). I think a simple 'include' is needed, but I'm guessing a lot of them will be needed as it looks like this might affect all plugins, not just the 'explode' one...

**Comment by ghost** [comment]
Since they're not used, replacing these lines:

```php
$path = 'plugins/';
$module = 'feeds_tamper';
```

in `feeds_tamper.plugins.inc` with:

```php
$plugins = backdrop_get_path('module', 'feeds_tamper') . '/plugins/*.inc';
foreach (glob($plugins) as $plugin) {
  include_once $plugin;
}
```

seems to work. Not sure if that's the best solution though...

**Comment by herbdool** [comment]
Oops, I had only checked the callback.

I don't want to do an include here since it's supposed to be plugable. We'll need to include once it's gathered all the info hooks data.

**Comment by herbdool** [comment]
I've pushed a fix for that.

My approach has been for each info hook to define the path and file so we can include it wherever we gather up all the plugins. A different approach from what you describe above which requires a particular directory.
